title: "Xiran Liu"
email: "xiran_liu1@brown.edu"
description: "Academic website for Xiran Liu"
url: "https://xr-cc.github.io"
baseurl: ""

markdown: kramdown
permalink: pretty
timezone: America/New_York

kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: compressed

exclude:
  - .devcontainer
  - .github/ISSUE_TEMPLATE
  - Dockerfile
  - docker-compose.yaml
  - Gemfile.lock
  - LICENSE
  - node_modules
  - package.json
  - README.old.md
  - talkmap
  - talkmap.ipynb
  - talkmap.py
  - talkmap_out.ipynb
  - vendor

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
